export const metadata = [
  {
    id: 1,
    colname: 'name',
    title: 'Name',
    hAlign: 'left',
    dAlign: 'left',
    width: '20%',
    textColor: '#FFF',
    bgColor: '',
    sort: true,
    filter: true,
    formatFn: null,
  },
  {
    id: 2,
    colname: 'address',
    title: 'Street Address',
    hAlign: 'left',
    dAlign: 'left',
    width: '20%',
    textColor: '#FFF',
    bgColor: '',
    sort: true,
    filter: true,
    formatFn: null,
  },
  {
    id: 3,
    colname: 'city',
    title: 'City',
    hAlign: 'left',
    dAlign: 'left',
    width: '15%',
    textColor: '#FFF',
    bgColor: '',
    sort: true,
    filter: false,
    formatFn: null,
  },
  {
    id: 4,
    colname: 'state',
    title: 'State',
    hAlign: 'left',
    dAlign: 'left',
    width: '10%',
    textColor: '#FFF',
    bgColor: '',
    sort: false,
    filter: true,
    formatFn: null,
  },
  {
    id: 5,
    colname: 'zipcode',
    title: 'Zip Code',
    hAlign: 'left',
    dAlign: 'left',
    width: '13%',
    textColor: '#FFF',
    bgColor: '',
    sort: false,
    filter: true,
    formatFn: null,
  },
  {
    id: 6,
    colname: 'age',
    title: 'Age',
    hAlign: 'center',
    dAlign: 'center',
    width: '7%',
    textColor: '#FFF',
    bgColor: '',
    sort: true,
    filter: true,
    formatFn: null,
  },
  {
    id: 7,
    colname: 'salary',
    title: 'Salary',
    hAlign: 'right',
    dAlign: 'right',
    width: '10%',
    textColor: '#FFF',
    bgColor: '',
    sort: true,
    filter: true,
    formatFn: null,
  },
  {
    id: 8,
    colname: 'hiredate',
    title: 'Hire Date',
    hAlign: 'left',
    dAlign: 'left',
    width: '15%',
    textColor: '#FFF',
    bgColor: '',
    sort: true,
    filter: true,
  },
];
